@startuml
title CRUD clinic information

actor Manager
participant System
Database Database

Manager -> System: Create Clinic Information
activate System
System -> Database: Save Clinic Information
activate Database
Database --> System: Confirmation
deactivate Database
System --> Manager: Success Message
deactivate System

Manager -> System: Read Clinic Information
activate System
System -> Database: Retrieve Clinic Information
activate Database
Database --> System: Clinic Information Data
deactivate Database
System --> Manager: Clinic Information
deactivate System

Manager -> System: Update Clinic Information
activate System
System -> Database: Modify Clinic Information
activate Database
Database --> System: Confirmation
deactivate Database
System --> Manager: Success Message
deactivate System

Manager -> System: Delete Clinic Information
activate System
System -> Database: Remove Clinic Information
activate Database
Database --> System: Confirmation
deactivate Database
System --> Manager: Success Message
deactivate System

@enduml
