@startuml
title CRUD Prescription Sequence Diagram

Actor Doctor
participant PrescriptionSystem

Doctor -> PrescriptionSystem: Create prescription
activate Doctor
activate PrescriptionSystem
PrescriptionSystem --> Doctor: Confirm prescription creation
deactivate Doctor
deactivate PrescriptionSystem

Doctor -> PrescriptionSystem: Get all prescriptions
activate Doctor
activate PrescriptionSystem
PrescriptionSystem --> Doctor: Send all prescriptions
deactivate Doctor
deactivate PrescriptionSystem

Doctor -> PrescriptionSystem: Get specific prescription
activate Doctor
activate PrescriptionSystem
PrescriptionSystem --> Doctor: Send specific prescription
deactivate Doctor
deactivate PrescriptionSystem

Doctor -> PrescriptionSystem: Request to update prescription
activate Doctor
activate PrescriptionSystem
PrescriptionSystem --> Doctor: Accept or reject request to update prescription
PrescriptionSystem --> Doctor: Send updated prescription
deactivate Doctor
deactivate PrescriptionSystem

Doctor -> PrescriptionSystem: Request to delete prescription
activate Doctor
activate PrescriptionSystem
PrescriptionSystem --> Doctor: Accept or reject request to delete prescription
PrescriptionSystem --> Doctor: Confirm prescription deletion
deactivate Doctor
deactivate PrescriptionSystem
@enduml
