@startuml
Title CRUD the information of patient
actor User
participant System
Database database

User -> System: Sends request to create, read, update, or delete patient information
activate User
activate System
User -> System: Enters patient data
System -> database: Require to get data
activate database
database --> System: Send data
deactivate database
System -> User: Confirms patient data
User -> System: Confirms to create, read, update, or delete patient information
System-> database: Save data
activate database
database --> System: Confirmation
deactivate database
System --> User: Returns result of creating, reading, updating, or deleting patient information
deactivate System
deactivate User
@enduml
