@startuml
title CRUD marketing sequence diagram with manager

Actor User
participant Manager
participant MarketingSystem

User -> Manager: Request to create marketing campaign
activate Manager
Manager --> User: Approve or reject request
User -> Manager: Confirm marketing campaign creation (if approved)
Manager -> MarketingSystem: Create marketing campaign (if approved)
activate MarketingSystem
MarketingSystem --> Manager: Confirmation
deactivate MarketingSystem
deactivate Manager

User -> Manager: Request to get all marketing campaigns
activate Manager
Manager --> User: Approve or reject request
User -> Manager: Confirm request (if approved)
Manager -> MarketingSystem: Get all marketing campaigns (if approved)
activate MarketingSystem
MarketingSystem --> Manager: Send all marketing campaigns
deactivate MarketingSystem
deactivate Manager

User -> Manager: Request to get specific marketing campaign
activate Manager
Manager --> User: Approve or reject request
User -> Manager: Confirm request (if approved)
Manager -> MarketingSystem: Get specific marketing campaign (if approved)
activate MarketingSystem
MarketingSystem --> Manager: Send specific marketing campaign
deactivate MarketingSystem
deactivate Manager

User -> Manager: Request to update marketing campaign
activate Manager
Manager --> User: Approve or reject request
User -> Manager: Confirm marketing campaign update (if approved)
Manager -> MarketingSystem: Update marketing campaign (if approved)
activate MarketingSystem
MarketingSystem --> Manager: Confirmation
deactivate MarketingSystem
deactivate Manager

User -> Manager: Request to delete marketing campaign
activate Manager
Manager --> User: Approve or reject request
User -> Manager: Confirm request (if approved)
Manager -> MarketingSystem: Delete marketing campaign (if approved)
activate MarketingSystem
MarketingSystem --> Manager: Confirmation
deactivate MarketingSystem
deactivate Manager
@enduml
