@startuml
Title CRUD inventory
Actor Manager
participant System
Database Warehouse

Manager -> System: Adds new inventory item
activate Manager
activate System
System -> Warehouse: Stores inventory item
activate Warehouse
Warehouse --> System: Confirms inventory item stored
deactivate Warehouse
System --> Manager: Returns inventory item ID
deactivate System
deactivate Manager

Manager -> System: Updates inventory item
activate Manager
activate System
System -> Warehouse: Updates inventory item
activate Warehouse
Warehouse --> System: Confirms inventory item updated
deactivate Warehouse
System --> Manager: Returns inventory item updated
deactivate System
deactivate Manager

Manager -> System: Deletes inventory item
activate Manager
activate System
System -> Warehouse: Deletes inventory item
activate Warehouse
Warehouse --> System: Confirms inventory item deleted
deactivate Warehouse
System --> Manager: Returns inventory item deleted
deactivate System
deactivate Manager

Manager -> System: Requests inventory report
activate Manager
activate System
System -> Warehouse: Retrieves inventory report
activate Warehouse
Warehouse --> System: Returns inventory report
deactivate Warehouse
System --> Manager: Displays inventory report
deactivate System
deactivate Manager
@enduml
