@startuml
title Manage Schedule of Employee Sequence Diagram

Actor Manager
participant SchedulingSystem
participant Employee

Manager -> SchedulingSystem: Creates or updates employee schedule
activate Manager
activate SchedulingSystem

SchedulingSystem -> Employee: Sends notification of updated schedule
activate Employee
Employee --> SchedulingSystem: Confirms or disputes schedule update
deactivate Employee
SchedulingSystem --> Manager: Confirms or disputes schedule update
Manager -> SchedulingSystem: Approves or denies schedule update
SchedulingSystem -> Employee: Confirms or denies schedule update
activate Employee
deactivate SchedulingSystem
deactivate Manager
@enduml
