@startuml
title Pay Dental Clinic Fees Sequence Diagram

Actor Patient
participant DentalClinicSystem

Patient -> DentalClinicSystem: Request to pay dental clinic fees
DentalClinicSystem --> Patient: Display payment BiLL
Patient -> DentalClinicSystem: Approve or deny BiLL
DentalClinicSystem --> Patient: Process payment ( if approved)
DentalClinicSystem --> Patient: Confirm payment success

@enduml