@startuml
title Print Bill Sequence Diagram

Actor patient
participant BillingSystem
participant Printer

patient -> BillingSystem: Request to print bill
activate patient
activate BillingSystem

BillingSystem -> Printer: Send bill to printer
activate Printer
Printer --> BillingSystem: Confirm bill printing
deactivate Printer

BillingSystem --> patient: Confirm bill printing
deactivate BillingSystem
deactivate patient
@enduml
