@startuml
Title Send Messenger for Patient
actor employee
participant System

employee -> System: Enter Patient information and message, email content
activate System
System -> System: Create message, email
System -> Patient: Send message, email to Patient
activate Patient
deactivate System
deactivate Patient
@enduml
