@startuml
title Class Diagram to Support Dental Clinic Management with Manager Class

class DentalClinic {
  + id: int
  + name: string
  + address: string
  + phone: string
  + email: string
  + website: string

  + patients: List<Patient>
  + staff: List<Staff>
  + appointments: List<Appointment>
  + treatments: List<Treatment>
  + invoices: List<Invoice>
  + manager: Manager

  + addPatient(patient: Patient)
  + removePatient(patient: Patient)
  + getPatients(): List<Patient>

  + addStaff(staff: Staff)
  + removeStaff(staff: Staff)
  + getStaff(): List<Staff>

  + bookAppointment(patient: Patient, staff: Staff, treatment: Treatment, date: Date, time: Time)
  + cancelAppointment(appointment: Appointment)
  + getAppointments(): List<Appointment>

  + addTreatment(treatment: Treatment)
  + removeTreatment(treatment: Treatment)
  + getTreatments(): List<Treatment>

  + generateInvoice(patient: Patient, treatment: Treatment)
  + getInvoices(): List<Invoice>
}

class Manager {
  + id: int
  + name: string
  + jobTitle: string

  + dentalClinic: DentalClinic

  + layoff(staff: Staff)
  + calculate_salary(staff: Staff)
  + generate_finance_report()
  + monitor_financial_revenue()
}

class Patient {
  + id: int
  + name: string
  + dateOfBirth: Date
  + address: string
  + phone: string
  + email: string
  + insuranceInformation: string

  + appointments: List<Appointment>

  + bookAppointment(staff: Staff, treatment: Treatment, date: Date, time: Time)
  + cancelAppointment(appointment: Appointment)
  + getAppointments(): List<Appointment>
}

class Staff {
  + id: int
  + name: string
  + address: string
  + salary: money
  + phone: string
  + email: string
  + jobTitle: string
  + qualifications: string

  + appointments: List<Appointment>

  + bookAppointment(patient: Patient, treatment: Treatment, date: Date, time: Time)
  + cancelAppointment(appointment: Appointment)
  + getAppointments(): List<Appointment>
}

class Doctor {
  + specialization: string
}

class OrdinaryEmployee {
  + department: string
}

class Appointment {
  + id: int
  + patient: Patient
  + staff: Staff
  + treatment: Treatment
  + date: Date
  + time: Time
  + status: string

  + cancel()
  + complete()
}

class Treatment {
  + id: int
  + name: string
  + description: string
  + price: float
  + NumOfDay: int

  + appointments: List<Appointment>
}

class Invoice {
  + id: int
  + patient: Patient
  + treatment: Treatment
  + amount: float
  + dateIssued: Date
  + dueDate: Date
  + status: string

  + pay()
  + bool checkStatus()
}
DentalClinic --|> Manager
DentalClinic "1" -- "n" Staff
Staff --|> Doctor
Staff --|> OrdinaryEmployee
Patient "1" -- "n" Appointment
Staff "1" -- "n" Appointment
Treatment "1" -- "n" Appointment
Patient "1" -- "n" Invoice
@enduml
